#!/bin/bash

sudo ./system_backup.sh
source ./system_config.sh
#sudo cp -rf ./boot/config-nomal.txt ./boot/config.txt.bak
sudo echo "hdmi_force_hotplug=1" >> ./boot/config.txt.bak
sudo cp -rf ./boot/config.txt.bak /boot/firmware/config.txt

sudo sync
sudo sync
sleep 2
#sudo cp -rf ./usr/modules-HDMI  /etc/modules
#sudo cp -rf ./usr/99-fbturbo.conf-HDMI  /usr/share/X11/xorg.conf.d/99-fbturbo.conf
#sudo cp ./boot/config-nomal.txt /boot/config.txt
#if [ -b /dev/mmcblk0p7 ]; then
#sudo cp ./usr/cmdline.txt-noobs /boot/cmdline.txt
#else
#sudo cp ./usr/cmdline.txt /boot/
#fi
#sudo cp ./usr/inittab /etc/
#echo "reboot now"

#sudo cp -rf ./usr/modules-HDMI  /etc/modules
#udo cp -rf ./usr/99-fbturbo.conf-HDMI  /usr/share/X11/xorg.conf.d/99-fbturbo.conf

#version=`lsb_release -r | awk -F ' '  '{printf $NF}'`

#if [[ "$version" < "20.04" ]]; then
#sudo cp -rf ./boot/config-nomal.txt ./boot/config.txt.bak
#else
#sudo cp -rf ./boot/config-nomal-20.04.txt ./boot/config.txt.bak
#fi
#sudo cp ./boot/config-nomal.txt /boot/config.txt
#if [ -b /dev/mmcblk0p7 ]; then
#sudo cp ./usr/cmdline.txt-noobs /boot/cmdline.txt
#else
#sudo cp ./usr/cmdline.txt /boot/
#fi
#sudo cp ./usr/inittab /etc/
echo "reboot now"
sudo reboot
